language: node_js
node_js:
    - "10.16.0"
dist: trusty

before_install: 
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
    - npm install

before_script:
    - npm install -g @angular/cli

script:
    - npm run webdriver-update
    - npm run webdriver-start
    - echo Running tests
    - npm run ci-e2e

addons:
    chrome: beta
