language: node_js
node_js:
    - "10.16.0"

install:
    - npm install

before_script:
    - npm install -g @angular/cli

script:
    - npm test
    - npm run webdriver-update
    - npm run webdriver-start
    - echo Running tests
    - npm run ci-e2e
